cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:recipe_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:recipe_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout')
]

dbms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('food.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path, re_path
from . import views

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'food'

urlpatterns = [

    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='main/index.html'), name='logout'),
    path('index/', views.index, name='index'),
    path('', views.home, name='home'),
    path('me/', views.profile, name='profile'),
    path('restaurants/', views.restaurants_view, name='res_list'),
    path('menu/<parameter>/', views.menu, name='menu'),
    path('contact/', views.contact, name='contact'),
    re_path(r'^search/$', views.search, name='search'),
    path('offers/', views.offers, name='offer'),
    path('place/<parameter>/', views.place, name='place'),
    path('pay/<parameter>/', views.pay, name='pay'),
    path('fav/<parameter>/', views.fav_add, name='fav_add'),
    path('favdel/<parameter>/', views.fav_del, name='fav_del'),

]

food/models.py
from django.db import models
from django.conf import settings
import uuid

# from phonenumber_field.modelfields import PhoneNumberField


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=30)

    def __str__(self):
        return format(self.user.username)


class Favourite(models.Model):
    user_name = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    res_name = models.ForeignKey('Restaurant', on_delete=models.CASCADE)
    is_favourite = models.BooleanField(default=False)

    @classmethod
    def create(cls, is_favourite):
        fav = cls(is_favourite=is_favourite)
        return fav

    class Meta:
        unique_together = ("user_name", "res_name")


class Restaurant(models.Model):
    name = models.CharField(max_length=20, unique=True)
    rating = models.IntegerField(default=0)
    image = models.ImageField(upload_to='restoimgs', blank=True)
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=30)

    def __str__(self):
        return format(self.name)


class Offer(models.Model):
    name = models.OneToOneField('Restaurant', on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return format(self.name)


class Recipe(models.Model):
    restaurant_name = models.ForeignKey('Restaurant', on_delete=models.CASCADE)
    recipe_name = models.CharField(max_length=20)
    recipe_description = models.CharField(max_length=20)
    recipe_price = models.IntegerField(default=0)
    recipe_image = models.ImageField(upload_to='recipe_imgs', blank=True)
    category = models.CharField(max_length=20, default=' ')

    class Meta:
        verbose_name_plural = "recipes"


class Order(models.Model):
    Oid = models.UUIDField(default=uuid.uuid4,unique=True, editable=False)
    first_name = models.CharField(max_length=50,default='')
    last_name = models.CharField(max_length=50,default='')
    email = models.EmailField(null=True)
    address = models.CharField(max_length=250,default='')
    postal_code = models.CharField(max_length=20,default='')
    city = models.CharField(max_length=100,default='')
    paid = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "orders"

    def __str__(self):
        return format(self.first_name)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Recipe, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price


class Delivery(models.Model):
    Delivery_no = models.IntegerField(primary_key=True)
    Dname = models.CharField(max_length=20)
    Drating = models.IntegerField(default=0)
    contact = models.CharField(max_length=10)

    class Meta:
        verbose_name_plural = "deliveries"


class PaymentInfo(models.Model):
    Cid = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    Pid = models.CharField(max_length=40)
    mode = models.CharField(max_length=20)
    NetPrice = models.IntegerField(default=0)

    @classmethod
    def create(cls,mode):
        payment = cls(mode=mode)
        return payment

    class Meta:
        verbose_name_plural = "payments"

food/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'postal_code', 'city']

food/views.py
from django.shortcuts import render, get_object_or_404
from .models import (Restaurant, 
					UserProfile, 
					Favourite, 
					Offer,
					OrderItem,
					Recipe,
					Order,
					Delivery,
					PaymentInfo)

from django.contrib.auth.models import User
from .forms import UserRegistrationForm
from django.contrib.auth.decorators import login_required
from cart.cart import Cart

list_fav = []


@login_required
def home(request):
	if request.method == 'GET':
		pop_restaurants = Restaurant.objects.all().filter(rating__range=(4,5))
		avg_restaurants = Restaurant.objects.all().filter(rating__range=(1,3))
		offer_zone = Offer.objects.all()
		return render(request,'main/home.html',{'pop_restaurants':pop_restaurants,'avg_restaurants':avg_restaurants,'offer_zone':offer_zone })


def index(request):
	if request.method == 'GET':
		return render(request,'main/index.html')


def register(request):
	if request.method == 'POST':
		user_form = UserRegistrationForm(request.POST)
		if user_form.is_valid():
			new_user = user_form.save(commit=False)
# Set the chosen password
			new_user.set_password(
			user_form.cleaned_data['password'])
# Save the User object
			new_user.save()
			UserProfile.objects.create(user=new_user)
			return render(request, 'account/register_done.html', {'new_user': new_user})
	else:
		user_form = UserRegistrationForm()
	return render(request, 'account/register.html',{'user_form': user_form})


def contact(request):
	if request.method == 'GET':
		return render(request,'contact.html')


@login_required
def restaurants_view(request):
	if request.method == 'GET':
		favourites = Favourite.objects.filter(user_name__user=request.user)
		restaurants = Restaurant.objects.order_by('-rating').exclude(name__in=list_fav)
		return render(request, 'food/restaurants.html', {'restaurants': restaurants, 'favourites': favourites})


@login_required
def menu(request, parameter):
	if request.method == 'GET':
		res_details = Restaurant.objects.filter(name=parameter)
		res_name = Restaurant.objects.get(name=parameter)
		try:
			off = Offer.objects.get(name__name=res_name.name)
		except Offer.DoesNotExist:
			off = None
		cart = Cart(request)
		for i in res_details:
			name = i.name
		recipe_details = Recipe.objects.filter(restaurant_name__name=name)
		return render(request, 'food/restaurantmenu.html', {'cart': cart, 'res_details': res_details, 'recipe_details': recipe_details,'offer_price':off})


@login_required
def profile(request):
	if request.method == 'GET':
		pres_user = request.user
		fav_res = Favourite.objects.filter(user_name__user=pres_user)
		orders = OrderItem.objects.filter(order__first_name=request.user.first_name)
		return render(request, 'account/profile.html', {'fav_res': fav_res,'orders':orders})


@login_required
def offers(request):
	if request.method == 'GET':
		restaurants = Restaurant.objects.all()
		my_offers = Offer.objects.all()
		return render(request, 'food/offers.html', {'my_offers': my_offers, 'restaurants': restaurants})


@login_required
def search(request):
	query = request.GET.get("q")
	if query:
		queryset_list = Restaurant.objects.filter(name__istartswith=query)
	else:
		queryset_list = {}
	return render(request, 'food/search_result.html', {'queryset_list': queryset_list})


@login_required
def place(request, parameter):
	if request.method == 'GET':
		place_resto = Restaurant.objects.filter(address__icontains=parameter)
	return render(request, 'food/brands_place.html', {'place_resto': place_resto})


@login_required
def pay(request, parameter):
	cart = Cart(request)
	order = get_object_or_404(Order, Oid=parameter)
	total = cart.get_total_price()
	if request.method == 'POST':
		method = request.POST.get("pay")
		obj = get_object_or_404(UserProfile, user=request.user)
		#user = request.user.first_name
		new = PaymentInfo.create(mode=method)
		new.Cid = obj
		new.Pid = parameter
		new.NetPrice = total
		new.save()
		order.paid = True
		order.save()
		delivery = Delivery.objects.order_by("?").first()
		cart.clear()
		return render(request, 'food/order_cooking.html',{'delivery':delivery})
	return render(request, 'food/pay.html',{'order':order,'total':total})


def fav_add(request, parameter):

	favorite = get_object_or_404(Restaurant, name=parameter)

	if request.method == 'POST':
		obj = get_object_or_404(UserProfile, user=request.user)
		new = Favourite.create(is_favourite=True)
		new.res_name = favorite
		new.user_name = obj
		new.save()
		list_fav.append(parameter)
		favourites = Favourite.objects.filter(user_name__user = request.user)
		restaurants = Restaurant.objects.order_by('-rating').exclude(name__in=list_fav)
		return render(request,'food/restaurants.html', {'restaurants':restaurants,'favourites':favourites})


def fav_del(request,parameter):
	if request.method =='POST':
		rem = Favourite.objects.filter(res_name__name=parameter)
		rem.delete()
		list_fav.remove(parameter)
		favourites = Favourite.objects.filter(user_name__user = request.user)
		restaurants = Restaurant.objects.order_by('-rating').exclude(name__in=list_fav)
		return render(request,'food/restaurants.html', {'restaurants':restaurants,'favourites':favourites})

food/templates/food/brands_place.html
{% extends 'base.html' %}
{% load static %}

{% block head %}


    <script type="text/javascript">  //to scroll to results

    $(document).ready(function () {
        // Handler for .ready() called.
        $('html, body').animate({
            scrollTop: $('#scroll').offset().top
        }, 3000);
    });
    </script>

    <script>
    function scrollWin() {
      window.scrollTo(0, 500);
    }
    </script>
{% endblock %}

{% block body %}

    <div class="box">
        <h1>Hungry ? </h1>
        <h4>Order food Online !</h4>
        <h4>Explore the best Restaurants in Your City</h4>
        <div class="arrow bounce">
            <i id="scroll_down" class="fas fa-arrow-down" onclick="scrollWin()"></i>
        </div>
    </div>


    <div class="content container" id="scroll">
        <h3>Brands in place</h3>
         <hr>
            <br><br>
            <div class="row">
            {% for restaurant in place_resto %}
                    <div class="col-md-3.5 pr-4">
                        <a href="/menu/{{ restaurant.id }}">
                        <div class="post">
                            <img src="{{restaurant.image.url}}" alt="chapathi" width="330px" height="220px" />
                            <h2 class="title"><a href="">{{ restaurant.name }}</a></h2>
                            <h5 class="post-text" >{{ restaurant.phone}}</h5>
                            <h5 class="post-text">{{ restaurant.address }}</h5>
                            <span><i class="fas fa-thumbs-up">  {{ restaurant.rating}} </i></span>
                            <br>
                        </div>
                        </a>
                    </div>
            {% endfor %}
            </div>

    </div>
{% endblock %}

food/templates/food/checkout.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
        <br>
        <br>
        <br>
        <br>
    {% if cart.get_total_price != 0 %}
    <ul>
        {% for item in cart %}
           <li>
               <p>{{ item.name }}</p>
               <p class="num"> ₹ {{ item.price }}</p>
           </li>
        {% endfor %}
    </ul>
    <h5><p class="price-total">subtotal {{ total }}</p></h5>

    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input class="btn btn-success" type="submit" value="Place Order"></p>
        {% csrf_token %}
    </form>

    {% else %}
        <p>Your Cart is empty .</p>
        <p>Good food is always cooking go <a href="{% url 'food:res_list' %}"> explore</a></p>
    {% endif %}
    </div>

        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
{% endblock %}

food/templates/food/offers.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    <script>
    function scrollWin() {
      window.scrollTo(0, 500);
    }
    </script>
{% endblock %}

{% block body %}

    <div class="box">
        <h1>Hungry ? </h1>
        <h4>Order food Online !</h4>
        <h4>Explore the best Restaurants in Your City</h4>
        <div class="arrow bounce">
            <i id="scroll_down" class="fas fa-arrow-down" onclick="scrollWin()"></i>
        </div>
    </div>



    <div class="content container">
            <div class="row">
            {% for offer in my_offers %}
                    <div class="col-md-3.5 pr-4">
                        <a href="/menu/{{ offer.name }}">
                            <div class="post">
                                <img src="{{offer.name.image.url}}" alt="chapathi" width="330px" height="220px" />
                                <h2 class="title"><a href="/menu/{{ offer.name.id }}">{{ offer.name }}</a></h2>
                                <h5><p class="post-text" >{{ offer.value}} %</p></h5>
                                <h5><p class="post-text">{{ offer.name.address }}</p></h5>
                                <span><i class="far fa-grin-stars"> {{ offer.name.rating}} </i></span>
                                <br>
                            </div>
                        </a>
                    </div>
            {% endfor %}
            </div>
     </div>
{% endblock %}

food/templates/food/order_cooking.html
{% extends "base.html" %}
{% block title %}
Thank you We have received your payment
{% endblock %}
{% block body %}
    <div class="container">
    <br><br><br><br>
<h1>Thank you We have received your payment</h1><br><br>
<p>Your order is being cooked in the kitchen</p>
    <br><br><br><br>
    <strong><p>Delivered by :</p></strong>
        <p>Delivery number -{{ delivery.Delivery_no }}</p>
        <p>Delivery Person -{{ delivery.Dname }}</p>
        <p>Contact Details -{{ delivery.contact }}</p>
        <p>Rating          -{{ delivery.Drating }}</p>
    <br><br><br><br>
    </div>
{% endblock %}

food/templates/food/pay.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
<br><br><br><br>
    <form action="." method="post">
        <strong><p>Pay Via</p></strong>
        <br>
        {%   csrf_token %}
        <input type="radio" name="pay" value="Debit Card" required="True" >Debit Card
         <br>
        <br>
        <input type="radio" name="pay" value="Net Banking">Net Banking
        <br>
        <br>
        <input type="radio" name="pay" value="UPI">UPI
        <br>
        <br>
        <input type="radio" name="pay" value="amazon pay">Amazon Pay
        <br><br>
        <p><input class="btn btn-success" type="submit" value="Pay ₹ {{ total }}"></p>
    </form>
    <p><a href="/home"> <button class="btn btn-dark">cancel and go to home</button></a> </p>
        </div>
    <br><br><br><br>
{%  endblock %}

food/templates/food/restaurantmenu.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <script>
    function scrollWin() {
      window.scrollTo(0, 200);
    }

    </script>
{% endblock %}


{% block body %}


<div class="box-blue">
    <i class="fas fa-heart"></i>
    {% for i in res_details %}
    <p><img src="{{ i.image.url }} " alt="WebP rules." width="280px" height="180px" />
    <h1>{{i.name}} </h1>
        {% if offer_price %}
            <h3>{{ offer_price.value }}% off on all recipes  </h3>
        {% endif %}
        <br><br>
    <h5 style="color: white;padding-left: 50px">{{i.address}}  | {{i.rating}} <i class="fas fa-star"></i></h5>

    {% endfor %}
    <div class="menu arrow bounce">
            <i id="scroll_down" class="fas fa-arrow-down" onclick="scrollWin()"></i>
    </div>

</div>

<div class="container-special">
    <div class="food" id="content">
            <div class="row" >
                {% for recipe in recipe_details %}
                    <div class="col-md-3.5 pr-4">
                        <div class="post">
							<img src="{{ recipe.recipe_image.url }}" alt="chapati"  />
                            <h2 class="title"><a href="">{{ recipe.recipe_name }}</a></h2>
                            <h5 class="post-text" >{{ recipe.recipe_description }} </h5>
                            <form action="{% url "cart:cart_add" recipe.id %}" method="post" class="button">

                                {% csrf_token %}
                                <button type="submit">
                                    <i class="fa fa-plus-circle" aria-hidden="true" type="submit"></i>
                                </button>
                            </form>
                            <form action="{% url "cart:cart_remove" recipe.id %}" method="post" class="button">
                                {% csrf_token %}
                                <button type="submit">
                                    <i class="fa fa-minus-circle" aria-hidden="true" type="submit"></i>
                                </button>
                            </form>
                            <h5 class="post-text">₹ {{ recipe.recipe_price }} </h5>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </div>   

    <div class="sidebar">
        <h1>Cart</h1>
        <hr style="border: 0;width: 96%;color: black;height: 1px;">
        <div class="items">
            {% if cart.get_total_price != 0 %}
                <ul class="cart_items">
                    {% for item in cart %}
                        {% with recipe=item.recipe %}
                            <li>
                                <p>{{ item.name }}</p>
                                <p class="num">₹ {{ item.price }}</p>
                                <p><a href="{% url "cart:cart_remove" recipe.id %}">Remove</a></p>
                            </li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            {% else %}
                <p>Your Cart is empty .</p>
                <p>Good food is always cooking go <a href="{% url 'food:res_list' %}"> explore</a></p>
            {% endif %}
                <hr>
        </div>
        <br>
        {% if cart.get_total_price != 0 %}
            <h5><p class="price-total" >subtotal {{ total }}</p></h5>
            <p class="post-text" >**Extra charges may apply</p>
            <a href="/cart/checkout"> <button class="btn btn-success"> CHECKOUT</button></a>
        {% endif %}
    </div>     
</div>




{% endblock %}

food/templates/food/restaurants.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <form class="search-bar" method="GET" action="{% url 'food:search' %}">

        <input class = "bar" type="text" name='q' placeholder="Enter restaurant name" value="{{ request.GET.q }}">
        <button class="search-btn" type="submit" ><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>

    <div class="content container">
             {%  if favourites %}
            <h1>Favourite Restaurants</h1>
            <br><br>
            <div class="row">
            {% for restaurant in favourites %}
                    <div class="col-md-3.5 pr-4">
                        <a href="/menu/{{ restaurant.res_name.name }}">
                            <div class="post">
                                <img src="{{restaurant.res_name.image.url}}" alt="chapathi" width="330px" height="220px" />
                                <h2 class="title"><a href="">{{ restaurant.res_name.name }}</a></h2>
                                <h5><p class="post-text" >contact -{{ restaurant.res_name.phone}}</p></h5>
                                <h5><p class="post-text">location -{{ restaurant.res_name.address }}</p></h5>
                                <span><i class="far fa-grin-stars"> {{ restaurant.res_name.rating}} </i></span>
                                <form action="{% url 'food:fav_del' restaurant.res_name.name %}" method="post" class="button">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fas fa-heart" style="color:red;border: none;" type="submit" name="fav"></i>
                                    </button>
                                </form>
                                <br>
                            </div>
                        </a>
                    </div>
            {% endfor %}


            </div>
{% endif %}


            <h1>Restaurants</h1>
            <br><br>
            <div class="row">
            {% for restaurant in restaurants %}

                    <div class="col-md-3.5 pr-4">
                        <a href="/menu/{{ restaurant.name }}">
                            <div class="post">
                                <img src="{{restaurant.image.url}}" alt="chapathi" width="330px" height="220px" />
                                <h2 class="title"><a href="">{{ restaurant.name }}</a></h2>
                                <h5><p class="post-text" >contact -{{ restaurant.phone}}</p></h5>
                                <h5><p class="post-text">location -{{ restaurant.address }}</p></h5>
                                <span><i class="far fa-grin-stars"> {{ restaurant.rating}} </i></span>
                                <form action="{% url 'food:fav_add' restaurant.name %}" method="post" class="button">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="far fa-heart"  type="submit" name="fav"></i>
                                    </button>
                                </form>
                                <br>
                            </div>
                        </a>
                    </div>
            {% endfor %}



            </div>
     </div>	
{% endblock %}

food/templates/food/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

    <script type="text/javascript">

    $(document).ready(function () {
        // Handler for .ready() called.
        $('html, body').animate({
            scrollTop: $('#scroll').offset().top
        }, 'slow');
    });
    </script>

    <script>
    function scrollWin() {
      window.scrollTo(0, 500);
    }
    </script>
{% endblock %}

{% block body %}

    <div class="box">
        <h1>Hungry ? </h1>
        <h4>Order food Online !</h4>
        <h4>Explore the best Restaurants in Your City</h4>
        <div class="arrow bounce">
            <i id="scroll_down" class="fas fa-arrow-down" onclick="scrollWin()"></i>
        </div>

    </div>


    <form class="search-bar" method="GET" action="{% url 'food:search' %}">

        <input class = "bar" type="text" name='q' placeholder="Enter restaurant name" value="{{ request.GET.q }}">
        <button class="search-btn" type="submit" ><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>

    <div class="content container" id="scroll">
            <h3>Search Result </h3>
            <hr>
            <br><br>
            {% if queryset_list %}
            <div class="row" >
            {% for restaurant in queryset_list %}
                    <div class="col-md-3.5 pr-4">
                        <a href="/menu/{{ restaurant.name }}">
                        <div class="post">
                                <img src="{{restaurant.image.url}}" alt="chapathi" width="330px" height="220px" />
                                <h2 class="title"><a href="">{{ restaurant.name }}</a></h2>
                                <h5 class="post-text" >{{ restaurant.phone}}</h5>
                                <h5 class="post-text">{{ restaurant.address }}</h5>
                                <span><i class="fas fa-thumbs-up">  {{ restaurant.rating}} </i></span>
                                <br>
                            </div>
                        </a>
                        </div>
                {% endfor %}
            </div>
            {% else %}
                    <h3>No restaurants with that name found :(</h3>
                    <br><br><br><br><br>
            {% endif %}

    </div>
{% endblock %}

food/templates/food/thank_order.html
{% extends "base.html" %}
{% block title %}
Thank you
{% endblock %}
{% block body %}
    <div class="container">
    <br><br><br><br>
<h1>Thank you</h1><br><br>
<p>Your order has been successfully completed. Your order number is
<strong>{{ order.Oid }}</strong>.</p>
    <br><br><br><br>
        <strong><p>In order to confirm your order make the payment <a href="{% url 'food:pay' order.Oid  %}">here</a></p></strong>
    <br><br><br><br>
    </div>
{% endblock %}